queues:
  - name: lineitem_rows
    capacity: 256

  - name: q1_result
    capacity: 64

stages:
  - name: lineitem_reader
    type: parquet_arrow_source
    threads: 2
    output_queue: lineitem_rows
    config:
      path: "data/tpch/sf10-parquet/lineitem.parquet"
      common:
        filesystem: FILE_SYSTEM_LOCAL
        compression: COMPRESSION_AUTO

  - name: q1_query
    type: datafusion_sql_transform
    threads: 4
    input_queues:
      - queue: lineitem_rows
        table: lineitem
    output_queue: q1_result
    config:
      sql: |
        SELECT
          l_returnflag,
          l_linestatus,
          sum(l_quantity) AS sum_qty,
          sum(l_extendedprice) AS sum_base_price,
          sum(l_extendedprice * (1 - l_discount)) AS sum_disc_price,
          sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) AS sum_charge,
          avg(l_quantity) AS avg_qty,
          avg(l_extendedprice) AS avg_price,
          avg(l_discount) AS avg_disc,
          count(*) AS count_order
        FROM lineitem
        WHERE l_shipdate <= DATE '1998-09-02'
        GROUP BY l_returnflag, l_linestatus
        ORDER BY l_returnflag, l_linestatus

  - name: q1_writer
    type: parquet_arrow_sink
    threads: 1
    input_queue: q1_result
    config:
      path: "data/tpch/sf10-results/tpch_q1.parquet"
      common:
        filesystem: FILE_SYSTEM_LOCAL
        compression: COMPRESSION_SNAPPY
